### ISSUE TITLE
app 교육진도 (세번쨰) 

### ISSUE THREAD

**Issue by numuduwer** [pangol/dapp101#6]
투표한 결과, Front에 반영하기 - Event 사용하기 에서 에러가 나서 진행이 안되고있습니다. 
오류내용( app.js 이벤트함수에서 에러났습니다. 콘솔창에 오류있는줄에는 오류가없어서 다시해보겠습니다.)

**Comment by pangol** [comment]
오류는 어떤 오류가 나왔을까요?
